Repository MicrosoftDocs/cloud-adoption-framework, pull requests merged in 2019-10, with the labels that each got.

#31 Update cloud-governance.md
  docs/organize/cloud-governance.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, organize/subsvc

#34 Update number of tags allowed per resource
  docs/ready/azure-setup-guide/organize-resources.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#28 updating readiness guide
  docs/ready/azure-readiness-guide/media/manage-access/role-examples.png
  docs/ready/azure-readiness-guide/organize-resources.md
Labels: assessing_(C&L), do-not-merge

#16 Updating content for Suggested Skills
  docs/ready/suggested-skills.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#15 Update content for Suggest Skills
  docs/plan/suggested-skills.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, plan/subsvc

#14 Updating content for Suggested Skills
  docs/strategy/suggested-skills.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, strategy/subsvc

#43 Grammar fix - remove dangling word
  docs/ready/expanded-scope/terraform-landing-zone.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, ready/subsvc
