Repository MicrosoftDocs/cloud-adoption-framework, pull requests merged in 2020-01, with the labels that each got.

#77 Fixed Recommended resource-type prefix for Storage
  docs/ready/azure-best-practices/naming-and-tagging.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#76 Update cloud-governance.md
  docs/organize/cloud-governance.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, organize/subsvc

#73 Consistency guidelines for naming conventions
  docs/ready/azure-best-practices/naming-and-tagging.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#69 Update operational-compliance.md
  docs/manage/azure-management-guide/operational-compliance.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, operate/subsvc

#68 Update inventory.md
  docs/manage/azure-management-guide/inventory.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, operate/subsvc

#61 Duplicate meta title "Secure and Manage"
  docs/migrate/migration-considerations/secure-and-manage/index.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, migrate/subsvc

#60 Duplicate meta title
  docs/migrate/about.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, migrate/subsvc

#50 word choice?
  docs/govern/cost-management/policy-statements.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, govern/subsvc

#45 Update rationalize.md
  docs/digital-estate/rationalize.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, plan/subsvc

#23 integrated security paragraph
  docs/getting-started/enable.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, overview/subsvc

#32 Update cloud-governance.md
  docs/organize/cloud-governance.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, organize/subsvc

#22 Add security context to cultural changes
  docs/getting-started/migrate.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, overview/subsvc

#21 add security drivers
  docs/getting-started/migrate.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, overview/subsvc

#20 tweaks: security + multi-cloud strategy
  docs/index.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, overview/subsvc

#10 Update operational-fitness-review.md
  docs/manage/operational-fitness-review.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, operate/subsvc

#83 Duplicate title fixed
  docs/strategy/suggested-skills.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, strategy/subsvc

#85 Duplicate title and description fixed
  docs/organize/suggested-skills.md
Labels: Change sent to author, assessing_(C&L), cloud-adoption-framework/svc, do-not-merge, organize/subsvc
