Repository MicrosoftDocs/cloud-adoption-framework, pull requests merged in 2020-06, with the labels that each got.

#206 Update implementation.md
  docs/ready/enterprise-scale/implementation.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#208 Update implementation-options.md
  docs/ready/landing-zone/implementation-options.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#212 word typo they..that
  docs/reference/fundamental-concepts/hosting-hierarchy.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#210 duplicate word typo
  docs/ready/enterprise-scale/design-principles.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#211 Update implementation guide
  docs/ready/enterprise-scale/implementation-guidelines.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#199 update template - project details
  docs/plan/template.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, plan/subsvc

#223 Update identity-and-access-management.md
  docs/ready/enterprise-scale/identity-and-access-management.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#224 Update management-group-and-subscription-organization.md
  docs/ready/enterprise-scale/management-group-and-subscription-organization.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#226 Update network-topology-and-connectivity.md
  docs/ready/enterprise-scale/network-topology-and-connectivity.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#235 formatting - fixing table problems
  docs/ready/enterprise-scale/implementation-guidelines.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, ready/subsvc
