Repository MicrosoftDocs/cloud-adoption-framework, pull requests merged in 2020-09, with the labels that each got.

#275 Update migrate.md
  docs/get-started/migrate.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, overview/subsvc

#280 Update contoso-migration-refactor-web-app-sql.md
  docs/migrate/azure-best-practices/contoso-migration-refactor-web-app-sql.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, migrate/subsvc

#281 Update contoso-migration-refactor-web-app-sql-managed-instance.md
  docs/migrate/azure-best-practices/contoso-migration-refactor-web-app-sql-managed-instance.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, migrate/subsvc

#282 Update migrate.md
  docs/migrate/azure-migration-guide/migrate.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, migrate/subsvc

#220 Add Business impact item to Business Input table
  docs/plan/workloads.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, plan/subsvc, ready-to-merge

#228 added 'why' to several ES network design recs
  docs/ready/enterprise-scale/network-topology-and-connectivity.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, ready-to-merge, ready/subsvc

#249 Update management-and-monitoring.md
  docs/ready/enterprise-scale/management-and-monitoring.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, ready-to-merge, ready/subsvc

#258 principles -> principals
  docs/migrate/azure-best-practices/migrate-best-practices-security-management.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, migrate/subsvc, ready-to-merge

#263 Added prefix for Virtual Network Peering and UDRs
  docs/ready/azure-best-practices/naming-and-tagging.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, ready-to-merge, ready/subsvc

#274 Add management group naming naming suggestion
  docs/ready/azure-best-practices/naming-and-tagging.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, ready-to-merge, ready/subsvc

#285 Update index.md
  docs/digital-estate/index.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, plan/subsvc, ready-to-merge

#163 AKS - Checklist
  docs/innovate/kubernetes/cluster-design-operations.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, innovate/subsvc

#286 Update cloud-adoption.md
  docs/get-started/team/cloud-adoption.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, overview/subsvc

#296 Update hub-spoke-network-topology.md
  docs/ready/azure-best-practices/hub-spoke-network-topology.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#298 failure, not failover
  docs/migrate/azure-best-practices/contoso-migration-rehost-vm-sql-managed-instance.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, migrate/subsvc

#303 Update management-and-monitoring.md
  docs/ready/enterprise-scale/management-and-monitoring.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, ready-to-merge, ready/subsvc

#305 Clarifying Platform Owner Role
  docs/ready/enterprise-scale/identity-and-access-management.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, ready-to-merge, ready/subsvc

#304 Added shared services section to Virtual WAN paragraph
  docs/ready/enterprise-scale/network-topology-and-connectivity.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, ready/subsvc, strategy/subsvc
