Repository MicrosoftDocs/cloud-adoption-framework, pull requests merged in 2020-10, with the labels that each got.

#307 Add Reduce carbon footprint as motivation
  docs/strategy/motivations.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, ready-to-merge, strategy/subsvc

#317 Update governance-of-resources.md
  includes/governance-of-resources.md
Labels: do-not-merge, review-team-triage

#326 spelling correction - processionals to professionals
  docs/security/security-top-10.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, reference/subsvc

#331 Fixing broken link on Sandbox guidance
  docs/ready/enterprise-scale/management-group-and-subscription-organization.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#336 Fix: wrong UPN suffix
  docs/migrate/azure-best-practices/contoso-migration-infrastructure.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, migrate/subsvc
