Repository MicrosoftDocs/cloud-adoption-framework, pull requests merged in 2020-07, with the labels that each got.

#242 Update Broken Links on Policy definition.
  docs/ready/enterprise-scale/implementation-guidelines.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#243 Update organize-resources.md
  docs/ready/azure-setup-guide/organize-resources.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#229 Update network-topology-and-connectivity.md
  docs/ready/enterprise-scale/network-topology-and-connectivity.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#245 Resolve syncing conflicts from repo_sync_working_branch to master
  docs/innovate/innovation-guide/adoption.md
  docs/innovate/innovation-guide/apps.md
  docs/innovate/innovation-guide/ci-cd.md
  docs/innovate/innovation-guide/data.md
  docs/innovate/innovation-guide/devices.md
  docs/innovate/innovation-guide/index.md
  docs/migrate/azure-migration-guide/assess.md
  docs/migrate/azure-migration-guide/assistance.md
  docs/migrate/azure-migration-guide/index.md
  docs/migrate/azure-migration-guide/manage-costs.md
  docs/migrate/azure-migration-guide/migrate.md
  docs/migrate/azure-migration-guide/optimize-and-transform.md
  docs/migrate/azure-migration-guide/prerequisites.md
  docs/migrate/azure-migration-guide/secure-and-manage.md
  docs/ready/azure-setup-guide/govern-org-compliance.md
  docs/ready/azure-setup-guide/index.md
  docs/ready/azure-setup-guide/monitoring-reporting.md
  docs/ready/azure-setup-guide/organize-resources.md
  docs/ready/azure-setup-guide/staying-current.md
  docs/ready/enterprise-scale/implementation-guidelines.md
  docs/toc.yml
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#252 Update organize-resources.md
  docs/ready/azure-setup-guide/organize-resources.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#253 Update index.md
  docs/ready/enterprise-scale/index.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#254 remove all references to Service Map
  docs/migrate/azure-best-practices/contoso-migration-oss-db-to-azure.md
  docs/migrate/azure-best-practices/contoso-migration-scale.md
  docs/migrate/azure-best-practices/contoso-migration-sql-server-db-to-azure.md
Labels: aq-pr-triaged, do-not-merge
