Repository MicrosoftDocs/cloud-adoption-framework, pull requests merged in 2021-06, with the labels that each got.

#495 Update optimize-ai-machine-learning-cost.md
  docs/ready/azure-best-practices/optimize-ai-machine-learning-cost.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#502 Update identity-and-access-management.md
  docs/ready/enterprise-scale/identity-and-access-management.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#499 Fix title in step #3
  docs/migrate/azure-best-practices/tailwind-migration-rehost-server-replication.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, migrate/subsvc

#489 Updated asset type to reflect rebranding
  docs/ready/azure-best-practices/resource-naming.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#504 Added links to toolkits + added Error Analysis
  docs/strategy/responsible-ai.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, strategy/subsvc

#522 Update eslz-platform-automation-and-devops.md
  docs/scenarios/wvd/eslz-platform-automation-and-devops.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, ready/subsvc
