Repository MicrosoftDocs/cloud-adoption-framework, pull requests merged in 2021-04, with the labels that each got.

#425 Custom roles are very limited.
  docs/ready/enterprise-scale/identity-and-access-management.md
Labels: Change sent to author, aq-pr-triaged, caf-review, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#455 Update analytics-solutions-netezza.md
  docs/migrate/azure-best-practices/analytics/analytics-solutions-netezza.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, migrate/subsvc

#461 Update resource-abbreviations.md
  docs/ready/azure-best-practices/resource-abbreviations.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, ready/subsvc
