Repository MicrosoftDocs/cloud-adoption-framework, pull requests merged in 2021-07, with the labels that each got.

#535 Update ai-machine-learning-mlops.md
  docs/ready/azure-best-practices/ai-machine-learning-mlops.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#540 Fix typo in migrate.md
  docs/scenarios/sap/migrate.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, migrate/subsvc

#536 Update contoso-migration-oss-db-to-azure.md
  docs/migrate/azure-best-practices/contoso-migration-oss-db-to-azure.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, migrate/subsvc

#529 Update enterprise-scale-landing-zone.md
  docs/scenarios/aks/enterprise-scale-landing-zone.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#534 Update resource-naming.md
  docs/ready/azure-best-practices/resource-naming.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#542 Update index.md
  docs/scenarios/wvd/index.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, strategy/subsvc

#544 Update enterprise-scale-landing-zone.md
  docs/scenarios/wvd/enterprise-scale-landing-zone.md
  docs/scenarios/wvd/eslz-business-continuity-and-disaster-recovery.md
  docs/scenarios/wvd/eslz-identity-and-access-management.md
  docs/scenarios/wvd/eslz-management-and-monitoring.md
  docs/scenarios/wvd/eslz-network-topology-and-connectivity.md
  docs/scenarios/wvd/eslz-platform-automation-and-devops.md
  docs/scenarios/wvd/govern.md
  docs/scenarios/wvd/index.md
  docs/scenarios/wvd/innovate.md
  docs/scenarios/wvd/manage.md
  docs/scenarios/wvd/migrate-deploy.md
  docs/scenarios/wvd/migrate-release.md
  docs/scenarios/wvd/plan.md
  docs/scenarios/wvd/proof-of-concept.md
  docs/scenarios/wvd/ready.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, migrate/subsvc, ready/subsvc

#545 Update Naming
  docs/scenarios/wvd/strategy.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#549 Update contoso-migration-oss-db-to-azure.md
  docs/migrate/azure-best-practices/contoso-migration-oss-db-to-azure.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, migrate/subsvc

#557 Update security.md as per issue #441
  docs/get-started/security.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, general/subsvc, ready-to-merge
