Repository MicrosoftDocs/cloud-adoption-framework, pull requests merged in 2021-12, with the labels that each got.

#667 Resolve syncing conflicts from repo_sync_working_branch to master
  .gitignore
  docs/ready/enterprise-scale/enterprise-enrollment-and-azure-ad-tenants.md
  docs/ready/enterprise-scale/index.md
  docs/resources/tools-templates.md
  docs/scenarios/data-management/images/bastion-architecture.png
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, ready/subsvc, general/subsvc

#674 Move recommended approach note to approach section
  docs/ready/enterprise-scale/dine-guidance.md
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, ready/subsvc

#681 Resolve syncing conflicts from repo_sync_working_branch to main
  docs/migrate/azure-best-practices/contoso-migration-scale.md
  docs/ready/azure-best-practices/naming-and-tagging.md
  docs/resources/tools-templates.md
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, general/subsvc

#685 Resolve repo sync error in PR 683
  docs/ready/enterprise-scale/management-and-monitoring.md
  docs/ready/enterprise-scale/management-group-and-subscription-organization.md
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, ready/subsvc

#686 Resolve syncing conflicts from repo_sync_working_branch to main
  docs/migrate/migration-considerations/migrate/index.md
  docs/ready/enterprise-scale/dine-guidance.md
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, ready/subsvc

#689 Fixed typo
  docs/scenarios/data-management/strategy.md
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, scenario/subsvc

#690 Fixed typo
  docs/scenarios/data-management/strategy.md
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, scenario/subsvc
