Repository MicrosoftDocs/cloud-adoption-framework, pull requests merged in 2021-05, with the labels that each got.

#462 Update transition.md
  docs/ready/enterprise-scale/transition.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#460 Suggested abbreviation for Azure Firewall Policy
  docs/ready/azure-best-practices/resource-abbreviations.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#470 Update eslz-network-topology-and-connectivity.md
  docs/scenarios/sap/eslz-network-topology-and-connectivity.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#482 Typo "Azure board"→"Azure Boards"
  docs/innovate/innovation-guide/adoption.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, innovate/subsvc

#488 add link to the ESLZ from the index page
  docs/scenarios/aks/index.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, general/subsvc
