Repository MicrosoftDocs/cloud-adoption-framework, pull requests merged in 2021-01, with the labels that each got.

#368 Duplicate
  docs/ready/azure-best-practices/resource-naming.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, ready-to-merge, ready/subsvc

#364 Update plan.md
  docs/scenarios/wvd/plan.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, migrate/subsvc, ready-to-merge

#355 Update index.md
  docs/organize/index.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, organize/subsvc, ready-to-merge

#354 Update resource-abbreviations.md
  docs/ready/azure-best-practices/resource-abbreviations.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, ready-to-merge, ready/subsvc

#346 Removed Microsoft.Authorization/*/write NetOps
  docs/ready/enterprise-scale/identity-and-access-management.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, ready-to-merge, ready/subsvc

#356 Typo "Jupyter notebook"→"Jupyter Notebook"
  docs/innovate/ai/machine-learning.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, innovate/subsvc

#379 Quick fix: capitalize letter
  docs/ready/enterprise-scale/architecture.md
Labels: Change sent to author, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#377 Update management-group-and-subscription-organization.md
  docs/ready/enterprise-scale/management-group-and-subscription-organization.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, ready-to-merge, ready/subsvc

#381 Update to date for content refresh
  docs/ready/enterprise-scale/network-topology-and-connectivity.md
Labels: Change sent to author, cloud-adoption-framework/svc, ready-to-merge, ready/subsvc
