Repository MicrosoftDocs/cloud-adoption-framework, pull requests merged in 2021-08, with the labels that each got.

#562 FIxing a few typos
  docs/ready/enterprise-scale/management-group-and-subscription-organization.md
Labels: Change sent to author, aq-pr-triaged, cloud-adoption-framework/svc, do-not-merge, ready/subsvc

#573 Added Sentinel References
  docs/manage/azure-management-guide/enhanced-baseline.md
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, aq-pr-triaged, manage/subsvc

#578 removed product feedback link
  docs/docfx.json
Labels: do-not-merge, review-team-triage

#580 Fixed misspelling of Security Center (upper right corner)
  docs/ready/enterprise-scale/media/lz-design.png
Labels: do-not-merge, review-team-triage

#581 Corrected a minor typo
  docs/scenarios/data-management/architectures/data-landing-zone-data-products.md
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, ready/subsvc

#572 Change Arc-enabled Kubernetes to the correct product name
  docs/scenarios/aks/azure-products.md
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, aq-pr-triaged, inactive, scenario/subsvc, keep-open

#570 Include Azure ML best practices guides links
  docs/ready/azure-best-practices/index.md
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, ready/subsvc, aq-pr-triaged, keep-open
