Repository MicrosoftDocs/cloud-adoption-framework, pull requests merged in 2022-11, with the labels that each got.

#1002 Update index.md
  docs/secure/index.md
Labels: Change sent to author, ready-to-merge, cloud-adoption-framework/svc, secure/subsvc

#1000 Update provider for AVD and add scaling plans
  docs/ready/azure-best-practices/resource-abbreviations.md
Labels: Change sent to author, ready-to-merge, cloud-adoption-framework/svc, ready/subsvc

#1008 Microsoft docs update
  docs/ready/landing-zone/design-area/resource-org-subscriptions.md
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, ready/subsvc
