Repository MicrosoftDocs/cloud-adoption-framework, pull requests merged in 2023-01, with the labels that each got.

#1044 URL not displaying properly
  docs/ready/considerations/devops-toolchain.md
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, ready/subsvc

#1058 additional information t of the Azure Compute Gallery
  docs/scenarios/wvd/eslz-business-continuity-and-disaster-recovery.md
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, aq-pr-triaged, scenario/subsvc, qualifies-for-auto-merge

#1060 Update environments.md
  docs/ready/considerations/environments.md
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, ready/subsvc, aq-pr-triaged, qualifies-for-auto-merge
