Repository MicrosoftDocs/cloud-adoption-framework, pull requests merged in 2023-08, with the labels that each got.

#1181 Update index.md - Increase readability
  docs/ready/landing-zone/index.md
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, ready/subsvc, aq-pr-triaged, inactive, needs-human-review, cact-review-in-progress, pending-content-team/business-approval

#1219 New - Add Key Vault Managed HSM abbreviation to docs
  docs/ready/azure-best-practices/resource-abbreviations.md
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, ready/subsvc, aq-pr-triaged, qualifies-for-auto-merge

#1222 Add legend for those marked as '*' as optional
  docs/migrate/azure-best-practices/contoso-migration-rds-to-wvd.md
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, migrate/subsvc, aq-pr-triaged, qualifies-for-auto-merge, pending-content-team/business-approval

#1218 Update: Added recommended authorization system for the Azure Key Vault
  docs/ready/landing-zone/design-area/encryption-and-keys.md
Labels: Change sent to author, ready-to-merge, cloud-adoption-framework/svc, ready/subsvc, aq-pr-triaged, qualifies-for-auto-merge, pending-content-team/business-approval

#1206 Update eslz-security-governance-and-compliance.md
  docs/scenarios/wvd/eslz-security-governance-and-compliance.md
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, aq-pr-triaged, scenario/subsvc, cact-review-in-progress, pending-content-team/business-approval

#1220 Added AVS to scenario-specific implementations table.md
  docs/ready/enterprise-scale/scenario-specific-enterprise-scale-landing-zones.md
Labels: Change sent to author, ready-to-merge, cloud-adoption-framework/svc, ready/subsvc, aq-pr-triaged, qualifies-for-auto-merge, pending-content-team/business-approval

#1228 Update analytics-solutions-teradata.md
  docs/migrate/azure-best-practices/analytics/analytics-solutions-teradata.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, qualifies-for-auto-merge, pending-content-team/business-approval, caf/svc, caf-methodology-adopt-migrate/subsvc

#1229 Update the entry for Azure Synapse Analytics Spark Pool in example abbreviations
  docs/ready/azure-best-practices/resource-abbreviations.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge, caf/svc, caf-methodology-ready/subsvc
