Repository MicrosoftDocs/cloud-adoption-framework, pull requests merged in 2023-06, with the labels that each got.

#1163 Customer story link is not available anymore [GE Aviation's Digital Group]
  docs/scenarios/hybrid/index.md
  docs/strategy/business-outcomes/performance-outcomes.md
  docs/strategy/motivations.md
Labels: Change sent to author, ready-to-merge, cloud-adoption-framework/svc, aq-pr-triaged, strategy/subsvc, needs-human-review, cact-review-in-progress, pending-content-team/business-approval

#1192 Update sandbox-environments.md - updated sentence and fixed spelling.
  docs/ready/considerations/sandbox-environments.md
Labels: Change sent to author, do-not-merge, cloud-adoption-framework/svc, ready/subsvc, qualifies-for-auto-merge

#1161 Update traditional-azure-networking-topology.md
  docs/ready/azure-best-practices/traditional-azure-networking-topology.md
Labels: Change sent to author, ready-to-merge, cloud-adoption-framework/svc, ready/subsvc, aq-pr-triaged, qualifies-for-auto-merge, cact-review-in-progress, pending-content-team/business-approval
