Repository MicrosoftDocs/cloud-adoption-framework, pull requests merged in 2024-05, with the labels that each got.

#1327 Update DocuTune configuration file
  .docutune/config/docutune-global-override.json
Labels: do-not-merge, review-team-triage

#1328 Update: Changed CARML reference to Azure Verified Modules
  docs/ready/considerations/devops-teams-topologies.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge, caf/svc, caf-methodology-ready/subsvc

#1330 Fix type-o in 'Plan for Enterprise Agreement enrollment'
  docs/ready/landing-zone/design-area/azure-billing-enterprise-agreement.md
Labels: Change sent to author, do-not-merge, qualifies-for-auto-merge, caf/svc, caf-alz/subsvc

#1332 Fix typo at automation.md
  docs/ready/considerations/automation.md
Labels: Change sent to author, do-not-merge, qualifies-for-auto-merge, caf/svc, caf-methodology-ready/subsvc
